<?php
require_once'config/config.php';
require_once'core/App.php';
require_once'core/Controller.php';
require_once'core/Database.php';
require_once'core/Flasher.php';
require_once'controllers/Login.php';
require_once'models/Login_model.php';
?>